services:
  #  app:
  #    build: .
  #    ports:
  #      - "8080:8080"
  #    environment:
  #      - OTEL_COLLECTOR_ENDPOINT=http://otel-collector:4317
  #      - SPRING_PROFILES_ACTIVE=docker
  #    depends_on:
  #      - otel-collector

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:0.120.0
    volumes:
      - ./otelCollector/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317"     # OTLP gRPC receiver
      - "4318:4318"     # OTLP http receiver
      - ":8888"     # Prometheus metrics exposed by the Collector
      - ":8889"     # Prometheus exporter metrics
      - ":13133"   # health_check extension
      - ":1888"     # pprof extension
      - ":55679"   # zpages extension
    depends_on:
      - jaeger
      - prometheus

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"  # Web UI
#      - "14250:14250"  # Model used by collector

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    extra_hosts:
      host.docker.internal: host-gateway

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3033:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elastic
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - ELASTIC_PASSWORD=changeme
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  #  logstash:
  #    image: docker.elastic.co/logstash/logstash:7.14.0
  #    volumes:
  #      - ./logstash/pipeline:/usr/share/logstash/pipeline
  #    ports:
  #      - "5044:5044"
  #    depends_on:
  #      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]
      - ELASTICSEARCH_USERNAME=kibana
      - ELASTICSEARCH_PASSWORD=changeme
    depends_on:
      - elasticsearch

volumes:
  es-data: